name: irc
version: 4.0.0-dev
authors:
- Kenneth Endfinger <kaendfinger@gmail.com>
- samrg472 <samrg472@gmail.com>
- TheMike <zeusintraining@gmail.com>
- Logan Gorence <loganjohngorence@gmail.com>
description: A beautiful all-purpose IRC library.
homepage: https://github.com/SpinlockLabs/irc.dart/
environment:
  sdk: ">=2.0.0"
dependencies:
  quiver: ">=2.0.0"
dev_dependencies:
  test: ">=1.3.0"
